spring:
  mail:
   host: smtp.qq.com
   username: 1306123139@qq.com
   password: mgsdhltldtfbggge
   properties:
     mail:
       smtp:
         auth: true
         starttls:
           enable: true
           required: true