server:
  port: 7070

spring:
  application:
    name: config-center
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaozhenzhi/spring-config-center
          ## searchPaths: config-center
